title: Martin Murphy Blog Test
description: Testing with Jekyll AsciiDoc Quickstart project.
baseurl: /blogtest/
exclude:
  - LICENSE.adoc
  - README.adoc
  - Gemfile
  - Gemfile.lock
  - Rakefile
asciidoc: {}
asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font
